### ISSUE TITLE
[Seek for Help] Questions on the destroy and repair process.

### ISSUE THREAD

**Issue by bing-zhao** [water-mirror/NeuLNS#9]
Thanks for providing the code. I tried to read your paper and understand as much as I can, but there are still a few questions I would like to consult you. 

1. What is and how to decide the size of M as in Eq. (7)? i.e., how many candidate nodes to destroy and repair. 

2. Just to check my understanding of the destroy and repair. Is the following example correct? 
If the current solution is [1, 2, 3, 4, 5] and the decoder return a list of candidate to remove as [4, 2]. Then the repaired solution is [1, 4, 3, 2, 5]. 

3. As read from the other issue and corresponding reply. A solution is in the format of a list [[route_of_veh_1], [route_of_veh_2], ... [route_of_veh_k]]. However, if I understand correctly, the input to the encoder (i.e., the current solution) is a list of node indices [n1, n2, ..., ni]. How to eventually distribute the solution among multiple vehicles? Because I don't find any elements under the primitive node embedding represents vehicle ID (Sec 3.1 of the paper). 

4. How is the initial solution generated? and how additional vehicles are being included into the solution (is there any intuitive example demonstrating the transition from one solution to another with either addition or removal of a vehicle)? 

I will appreciate if you can give some guidance. Thank you in advance!

**Comment by cburdea** [comment]
Hi! I had some of the questions myself and I was able to clarify them by going through the code. I will try to address your questions with the best of my knowledge:

1. M will be determined beforehand. In the code you have a parameter to adjust the amount of removed nodes. 

2. You are right in a way that the nodes are being removed but it does not necessarily mean that they will be switched. The PointerNetwork (Repair Operator) might output the same order as in the original input order.  

3. I hope I got your question right: By default, more vehicles than necessary will be used to solve the problem. You are right, there is no dedicated ID for each used vehicle. However, you can deduct the amount of used vehicles by analyzing the solutions; Each block could represents initially one vehicle. Subsequently all you need to do is to check the time windows (start and end) of each block. The amount of time wise parallel executed blocks will be your number of vehicles. 

4. The initial solution is randomly generated often using multiple vehicles.

Regarding your multiple vehicle understanding: 

Solution t: [1,2],[3,4],[5,6] <- Lets imagine 1 and 3 need to be served within a similar time frame and are located near to each other. Since 2 follows 1 though, the vehicle will not be able to reach 3 in the needed time. Therefore you will need a second vehicle operating the second block. Jobs 5 and 6 are due in the evening and can be therefore operated with one of the existing vehicles. 


Solution t+1: [1,3,2,4],[5,6] <- If we switch 2 and 3, the vehicle will be able to reach 3 in time and can then serve 2 and 4 afterwards and the need for a second vehicle is gone. The interpretation and amount of needed vehicles however needs to be done by yourself though.

Hope this helped!

**Comment by bing-zhao** [comment]
> Hi! I had some of the questions myself and I was able to clarify them by going through the code. I will try to address your questions with the best of my knowledge:
> 
> 1. M will be determined beforehand. In the code you have a parameter to adjust the amount of removed nodes.
> 2. You are right in a way that the nodes are being removed but it does not necessarily mean that they will be switched. The PointerNetwork (Repair Operator) might output the same order as in the original input order.
> 3. I hope I got your question right: By default, more vehicles than necessary will be used to solve the problem. You are right, there is no dedicated ID for each used vehicle. However, you can deduct the amount of used vehicles by analyzing the solutions; Each block could represents initially one vehicle. Subsequently all you need to do is to check the time windows (start and end) of each block. The amount of time wise parallel executed blocks will be your number of vehicles.
> 4. The initial solution is randomly generated often using multiple vehicles.
> 
> Regarding your multiple vehicle understanding:
> 
> Solution t: [1,2],[3,4],[5,6] <- Lets imagine 1 and 3 need to be served within a similar time frame and are located near to each other. Since 2 follows 1 though, the vehicle will not be able to reach 3 in the needed time. Therefore you will need a second vehicle operating the second block. Jobs 5 and 6 are due in the evening and can be therefore operated with one of the existing vehicles.
> 
> Solution t+1: [1,3,2,4],[5,6] <- If we switch 2 and 3, the vehicle will be able to reach 3 in time and can then serve 2 and 4 afterwards and the need for a second vehicle is gone. The interpretation and amount of needed vehicles however needs to be done by yourself though.
> 
> Hope this helped!

cburdea, thank you for the explanation!
